CLASS LHC_GOODSMMTHUITM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEGUIDSTOCK FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  GoodsMmtHuitm~CalculateGuidStock .
ENDCLASS.

CLASS LHC_GOODSMMTHUITM IMPLEMENTATION.
  METHOD CALCULATEGUIDSTOCK.
  ENDMETHOD.
ENDCLASS.
